test_01_pass|tests/tests_09_make_report/test_functions.py::test_01_pass|PASSED|8.939998224377632e-05|
test_03_fail|tests/tests_09_make_report/test_functions.py::test_03_fail|<ExceptionInfo AssertionError('assert False') tblen=28>|0.00012799998512491584|
test_05_xfail_passes|tests/tests_09_make_report/test_functions.py::test_05_xfail_passes|X-PASSED|8.979998528957367e-05|xfail
